/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/theCar.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/theCar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ANTENNE.geometry} material={materials['Material.009']} position={[0, 5.806, -0.885]} rotation={[-0.337, 0, 0]} />
      <mesh geometry={nodes['ANTENNE-BASE'].geometry} material={materials['Material.009']} position={[0, 5.726, -0.885]} />
      <mesh geometry={nodes['ASSUIS-GLACE3'].geometry} material={materials['Material.009']} position={[-0.566, 3.194, 1.139]} rotation={[0, 0, 0.094]} />
      <group position={[0, 1.65, 0]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[0, 1.65, 0]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.010']} />
      </group>
      <mesh geometry={nodes.COFFRE.geometry} material={materials['Material.001']} position={[0, 1.65, 0]} />
      <mesh geometry={nodes['CONSOLE-CENTRALE'].geometry} material={materials['Material.004']} position={[0.009, 2.052, -1.349]} />
      <mesh geometry={nodes.DASHBOARD.geometry} material={materials['Material.004']} position={[0, 1.65, 0]} />
      <mesh geometry={nodes.DOORS.geometry} material={materials['Material.001']} position={[2.22, 2.817, -1.017]} />
      <mesh geometry={nodes['ESSUIES-GLACE'].geometry} material={materials['Material.009']} position={[0.455, 3.116, 1.095]} rotation={[-0.002, 0.052, 1.493]} />
      <mesh geometry={nodes['ESSUIES-GLACE2'].geometry} material={materials['Material.009']} position={[-0.575, 3.192, 1.037]} rotation={[0, -0.012, 1.738]} />
      <mesh geometry={nodes.FAUTEUILS.geometry} material={materials['08 Turquoise Velvet']} position={[1.104, 1.962, -1.184]} />
      <mesh geometry={nodes['FENÊTRES-PORTIÈRES'].geometry} material={materials['Material.008']} position={[2.056, 4.091, -1.153]} />
      <mesh geometry={nodes['FEUX-ARRIÈRES'].geometry} material={materials['Material.005']} position={[2.104, 2.644, -3.605]} rotation={[-Math.PI, 0.143, 0]} />
      <mesh geometry={nodes['FEUX-AVANT'].geometry} material={materials['Material.006']} position={[0, 1.634, -0.001]} />
      <mesh geometry={nodes['PAR-CHOC_ARRIÈRE'].geometry} material={materials['Material.002']} position={[0, 1.018, -0.738]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes['PAR-CHOC_AVANT'].geometry} material={materials['Material.002']} position={[0, 1.84, 0.007]} />
      <mesh geometry={nodes.PARBRISE.geometry} material={materials.Material} position={[1.08, 4.054, 0.458]} />
      <mesh geometry={nodes['POIGNÉE-PORTE'].geometry} material={materials['Material.001']} position={[2.53, 2.707, -1.738]} />
      <group position={[-0.001, 2.195, -1.14]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.655, 0.954, -2.207]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['37 Corduroy B']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.655, 0.954, 1.383]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials['37 Corduroy B']} />
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes['SOL-COFFRE'].geometry} material={materials['Material.004']} position={[0, 3.097, 0]} />
      <mesh geometry={nodes['VITRE-ARRIÈRE'].geometry} material={materials['Material.008']} position={[0, 1.65, 0]} />
      <mesh geometry={nodes.VOLANT.geometry} material={materials['29 Dry Painted Dark']} position={[1.087, 2.93, -0.401]} rotation={[-1.112, 0, 0]} />
      <mesh geometry={nodes.VOLANT2.geometry} material={materials['29 Dry Painted Dark']} position={[1.087, 2.851, -0.195]} rotation={[0.423, 0, 0]} />
      <mesh geometry={nodes.VOLANT3.geometry} material={materials['29 Dry Painted Dark']} position={[0.927, 3.199, -0.33]} rotation={[0.53, -0.157, 2.097]} />
      <mesh geometry={nodes.VOLANT4.geometry} material={materials['29 Dry Painted Dark']} position={[0.992, 2.764, -0.58]} rotation={[0.534, -0.077, -1.925]} />
      <mesh geometry={nodes.VOLANT5.geometry} material={materials['29 Dry Painted Dark']} position={[1.087, 2.738, 0.057]} rotation={[0.423, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[2.43, 3.268, 0.664]} rotation={[0.198, 0, 0.24]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[2.886, 3.456, 0.281]} rotation={[0.198, 0, 0.24]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[-0.002, 4.851, 0.279]} rotation={[-0.275, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[-0.002, 4.787, 0.052]} rotation={[-0.275, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/theCar.glb')
