/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfolioJobTitle.glb -o components/Gltf/JobTitle.tsx -r public/models 
*/

import * as THREE from "three";
import React, { forwardRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Plane: THREE.Mesh;
        Text: THREE.Mesh;
    };
    materials: {
        ["Material.001"]: THREE.MeshStandardMaterial;
        ["Material.002"]: THREE.MeshStandardMaterial;
    };
};

export const JobTitle = forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
    (props, ref) => {
        const { nodes, materials } = useGLTF(
            "models/portfolioJobTitle.glb"
        ) as GLTFResult;

        useEffect(() => {
            materials["Material.001"].color = new THREE.Color("white");
            materials["Material.001"].emissive = new THREE.Color("white");
            materials["Material.001"].emissiveIntensity = 1;
        });
        return (
            <group {...props} dispose={null} ref={ref}>
                <mesh
                    geometry={nodes.Plane.geometry}
                    material={materials["Material.001"]}
                />
                <mesh
                    geometry={nodes.Text.geometry}
                    material={materials["Material.002"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            </group>
        );
    }
);

JobTitle.displayName = "JobTitle";

useGLTF.preload("models/portfolioJobTitle.glb");
